#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/SpyChibi.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "100x"
# logo text will only show when logo is missing.
logo_text = "Boilerplate"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "The Netherlands"
twitter = "https://twitter.com/SpyroSkylander_"
twitteruser = "SpyroSkylander_"
email = "joshuaslui0203@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
mainSections = ["blog"]
# about widget content
about_widget_content = "TesFlash is a blogging site maintained by Spyro, blogging about all things relevant at this very moment. TesFlash is not limited to any particular subject."
# footer content
footer_content = "TesFlash is based on a theme by ThemeFisher & Gethugothemes. See the source code [here](https://github.com/DeltaSLM/TesFlash)"
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to TesFlash"
image = "images/SpyChibi.png"
background_image = "/images/banner-bg-shape.svg"
content = "A blog about virtually anything relevant today, by Spyro, for everyone."
button_label = "About Me"
button_link = "about/"

# Advertise
[advertisement]
image = "images/psychops.png"
link = "https://psychops.eu/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/SpyroSkylander_"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/DeltaSLM"
